openapi: 3.0.1
info:
  title: p4pa-process-executions
  description: Api and Models
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /:
    post:
      summary: create-ingestion-flow-file
      tags:
        - ingestion-flow-file-controller
      operationId: createIngestionFlowFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestionFlowFileDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestionFlowFileDTO'
components:
  schemas:
    IngestionFlowFileDTO:
      type: object
      required:
        - organizationId
        - status
        - flowIdentifierCode
        - flagActive
      properties:
        ingestionFlowFileId:
          type: integer
          format: int64
        version:
          type: integer
          format: int32
        organizationId:
          type: integer
          format: int64
        status:
          type: string
          enum:
            - UPLOADED
            - PROCESSING
            - COMPLETED
            - ERROR
        flowIdentifierCode:
          type: string
        numTotalRows:
          type: integer
          format: int64
        numCorrectlyImportedRows:
          type: integer
          format: int64
        creationDate:
          type: string
          format: date-time
        lastUpdateDate:
          type: string
          format: date-time
        flagActive:
          type: boolean
        operatorExternalUserId:
          type: string
        flagSpontaneous:
          type: boolean
        filePath:
          type: string
        fileName:
          type: string
        pdfGenerated:
          type: integer
          format: int64
        codRequestToken:
          type: string
        codError:
          type: string
        pspIdentifier:
          type: string
        flowDateTime:
          type: string
          format: date-time
        fileSize:
          type: integer
          format: int64
        fileSourceCode:
          type: string
        discardFileName:
          type: string
