openapi: 3.0.1
info:
  title: p4pa-process-executions
  description: Api and Models
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /ingestion-flow-files:
    post:
      summary: create-ingestion-flow-file
      tags:
        - ingestion-flow-file-controller
      operationId: createIngestionFlowFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestionFlowFileRequestDTO'
        required: true
      responses:
        '201':
          description: OK
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    IngestionFlowFileRequestDTO:
      type: object
      required:
        - organizationId
        - filePathName
        - fileName
        - fileSize
        - flowFileType
        - fileOrigin
      properties:
        organizationId:
          type: integer
          format: int64
        filePathName:
          type: string
        fileName:
          type: string
        fileSize:
          type: integer
          format: int64
        flowFileType:
          type: string
          enum:
            - RECEIPT
            - RECEIPT_PAGOPA
            - PAYMENTS_REPORTING
            - TREASURY_OPI
            - TREASURY_CSV
            - TREASURY_XLS
            - TREASURY_POSTE
        flowDateTime:
          type: string
          format: date-time
        pspIdentifier:
          type: string
        fileOrigin:
          type: string
