package it.gov.pagopa.pu.processecexutions.enums;

public enum IngestionFlowFileTypeEnum {
  RECEIPT,
  RECEIPT_PAGOPA,
  PAYMENTS_REPORTING,
  PAYMENTS_REPORTING_PAGOPA,
  TREASURY_OPI,
  TREASURY_CSV,
  TREASURY_XLS,
  TREASURY_POSTE,
  TREASURY_CSV_COMPLETE,
  DP_INSTALLMENTS,
  PAYMENT_NOTIFICATION,
  ORGANIZATIONS,
  ORGANIZATIONS_SIL_SERVICE,
  DEBT_POSITIONS_TYPE,
  DEBT_POSITIONS_TYPE_ORG,
  DEBT_POSITIONS_TYPE_ORG_OPERATORS,
  ASSESSMENTS
}

