apiVersion: v2
name: p4pa-process-executions
description: p4pa-process-executions
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 5.9.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
